pipeline {
    agent any
    tools {
        maven 'Apache Maven 3.9.9' // Use the name you configured in Global Tool Configuration
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t zreyyes.jfrog.io/springapp-docker/springapp:v1 .'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push zreyyes.jfrog.io/springapp-docker/springapp:v1'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
